config/routes.rb
Rails.application.routes.draw do
  resources :attractions, except: [:show]
  resources :shares, only: [:index] do
    collection do
      match 'send_attractions' => 'shares#send_attractions', via: [:post], as: :send_attractions
    end
  end

  devise_for :users, skip: [:registrations]

  as :user do
    match '/users/sign_up' => 'devise/registrations#new', via: :get, as: :new_user_registration
    match '/users' => 'devise/registrations#create', via: :post, as: :user_registration
  end

  root to: "home#index"

  resources :tools, only: [] do
    collection do
      match 'user_attractions' => 'tools#user_attractions', via: :get, as: :user_attractions
      match 'fetch_attractions' => 'tools#fetch_attractions', via: :get, as: :fetch_attractions
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user = User.new)
    if user.admin?
      can :manage, :all
    else
      can :manage, :attractions
      can :manage, :shares
    end
  end
end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
  belongs_to :user

  validates :name, :due_date, :due_time, :user, presence: true

  scope :find_last, ->(user_id) { where(:user_id => user_id).order("due_date desc, due_time desc")}

  def merge_date_time
    return DateTime.new(self.due_date.year, self.due_date.month,
      self.due_date.day, self.due_time.hour, self.due_time.min,
      self.due_time.sec, self.due_time.zone)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable, :trackable

  def admin?
    self.admin
  end

  def username
    self.email[/[^@]+/]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    attraction = Attraction.find_last(current_user).first
    if !attraction.nil? and attraction.merge_date_time.strftime("%Y-%m-%d %H:%M") > Time.now.strftime("%Y-%m-%d %H:%M")
      flash[:toast] = "Sua próxima atração hoje é às #{attraction.due_time.strftime("%H:%M")}"
    end

    attractions_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:toast] = exception.message
    redirect_to attractions_path
  end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html

  def index
    @attractions = Attraction.find_last(current_user)
    respond_with(@attractions)
  end

  def new
    @attraction = Attraction.new
    respond_with(@attraction)
  end

  def edit
  end

  def create
    @attraction = Attraction.new(attraction_params)
    @attraction.user = current_user

    if @attraction.save
      flash[:toast] = "Atração criada com sucesso!"
      redirect_to attractions_path
    else
      flash[:toast] = "Houve problemas ao criar uma nova atração."
      render :new
    end
  end

  def update
    if @attraction.update(attraction_params)
      flash[:toast] = "Atração atualizada com sucesso!"
      redirect_to attractions_path
    else
      flash[:toast] = "Houve problemas ao editar a atração."
      render :edit
    end
  end

  def destroy
    @attraction.destroy

    flash[:toast] = "Atração removida com sucesso!"

    redirect_to attractions_path
  end

  private
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    def attraction_params
      params[:attraction][:due_date] = params[:attraction][:due_date_submit] if !params[:attraction][:due_date_submit].nil?
      params.require(:attraction).permit(:name, :midia, :due_date, :due_time)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  layout 'home'

  def index
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def index
    @users = User.where("id != ?", current_user.id)
    @attractions = Attraction.find_last(current_user)
  end

  def send_attractions
    if params[:share].nil?
      flash[:toast] = "Selecione pelo menos uma atração e um usuário para compartilhar"
      return render :index
    end

    send_params = share_params
    if send_params[:attraction_ids].nil?
      flash[:toast] = "Selecione pelo menos uma atração para compartilhar"
      return render :index
    elsif send_params[:user_ids].nil?
      flash[:toast] = "Selecione pelo menos um usuário para compartilhar"
      return render :index
    end

    send_params[:user_ids].each do |user_id|
      ShareMailer.share(user_id, send_params[:attraction_ids]).deliver_now
    end

    flash[:toast] = "Compartilhado com sucesso!"
    redirect_to shares_path
  end

  private
    def share_params
      params[:share][:attraction_ids] = params[:share][:attraction_ids].flatten.uniq if !params[:share][:attraction_ids].nil?
      params[:share][:user_ids] = params[:share][:user_ids].flatten.uniq if !params[:share][:user_ids].nil?
      params.require(:share).permit(attraction_ids: [], user_ids: [])
    end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :class => ToolsController

  def user_attractions
    @users = User.where("id != ?", current_user.id)
  end

  def fetch_attractions
    @user = User.find(params[:user_id])
    @attractions = Attraction.find_last(@user)
    respond_to do |format|
        format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_error_messages(errors)
    message = ""

    errors.each do |error|
      message << error + ", "
    end

    return message[0.. message.length-3]
  end

  def set_classes_for_input(invalid)
    return invalid ? "validate invalid" : "validate"
  end
end

app/views/attractions/_form.html.haml
= form_for @attraction, html: {class: "col s12 form"} do |f|
  .row
    .input-field.col.s6
      - invalid = !@attraction.errors.messages[:name].blank?
      = f.label :name
      = f.text_field :name, class: set_classes_for_input(invalid)
      - if invalid
        %em.invalid
          = show_error_messages(@attraction.errors.messages[:name])
    .input-field.col.s6
      - invalid = !@attraction.errors.messages[:midia].blank?
      = f.label :midia
      = f.text_field :midia, class: set_classes_for_input(invalid)
      - if invalid
        %em.invalid
          = show_error_messages(@attraction.errors.messages[:midia])
  .row
    .input-field.col.s6
      - invalid = !@attraction.errors.messages[:due_date].blank?
      = f.label :due_date
      = f.text_field :due_date, class: "datepicker #{set_classes_for_input(invalid)}", value: (l(f.object.due_date) if !f.object.due_date.nil?)
      - if invalid
        %em.invalid
          = show_error_messages(@attraction.errors.messages[:due_date])
    .input-field.col.s6
      - invalid = !@attraction.errors.messages[:due_time].blank?
      = f.label :due_time
      = f.text_field :due_time, class: "timepicker #{set_classes_for_input(invalid)}"
      - if invalid
        %em.invalid
          = show_error_messages(@attraction.errors.messages[:due_time])
  = render partial:'layouts/form_action', :locals => {:f => f}

app/views/attractions/edit.html.haml
%h2.header
  = "Edição da Atração #{@attraction.name}"
.divider
= render 'form'

app/views/attractions/index.html.haml
.valign-wrapper
  %h2.header.col.s10
    Lista de Atrações
  = link_to 'Criar!', new_attraction_path, class: 'btn waves-effect waves-light green col.s2 tooltipped valign', data: {position: "bottom", delay: 50, tooltip: "Criar nova Atração"}
.divider
.row
  - if @attractions.size > 0
    %table.bordered.hoverable
      %thead
        %th.col.s4
          Nome
        %th.col.s2
          Midia
        %th.col.s4
          Data e Hora
        %th.col.s1
      %tbody
      - @attractions.each do |attraction|
        %tr
          %td.col.s4
            = attraction.name
          %td.col.s2
            = attraction.midia
          %td.col.s4
            = "#{attraction.merge_date_time.strftime("%d/%m/%Y %H:%M")}"
          %td.col.s1
            = link_to "Editar", edit_attraction_path(attraction), class: 'tooltipped', data: {position: "bottom", delay: 50, tooltip: "Editar #{attraction.name}"}
  - else
    %div.col.s12.card-panel
      %p.blue-text.text-darken-2
        Você ainda não possui atrações cadastradas
        = link_to "clique aqui", new_attraction_path, class: "tooltipped", data: {position: "bottom", delay: 50, tooltip: "Criar nova Atração"}
        para criar a primeira!

app/views/attractions/new.html.haml
%h2.header
  Nova Atração
.divider
= render 'form'

app/views/home/index.html.haml
#index-banner.parallax-container
  .section.no-pad-bot
    .container
      %br/
      %br/
      %h1.header.center.teal-text.text-lighten-2 Organizador de Atrações
      .row.center
        %h5.header.col.s12.light Um aplicativo moderno para você organizar as suas atrações e compartilhar com as pessoas
      .row.center
        %a#download-button.btn-large.waves-effect.waves-light.teal.lighten-1{:href => "#{new_user_registration_path}"} CRIE SUA CONTA
      %br/
      %br/
  .parallax
    = image_tag "background_1.jpg"

app/views/layouts/_form_action.html.haml
.row
  .divider
  .actions
    .col.s4
      = link_to "Voltar para a listagem", attractions_path, class: "btn waves-effect waves-light blue"
    .col.s8
      - if !f.object.new_record?
        .offset-s6.col.s3
          = link_to "Excluir", attraction_path(@attraction), :method => :delete, :data => {confirm: "Você tem certeza?", position: "bottom", delay: 50, tooltip: "Excluir #{@attraction.name}"}, class: "btn waves-effect waves-light red tooltipped"
        .col.s3
          %button.btn.waves-effect.waves-light.green{type: :submit}
            Salvar
      - else
        .offset-s9.col.s3
          %button.btn.waves-effect.waves-light.green{type: :submit}
            Criar

app/views/layouts/_form_simple_action.html.haml
.row
  .divider
  .actions.col.offset-s10
    %button.btn.waves-effect.waves-light.green{type: :submit}
      = text

app/views/layouts/_header.html.haml
%nav
  .nav-wrapper
    %h1
      = link_to "Organizador de Atrações", user_signed_in? ? attractions_path : root_path, class: "brand-logo"
    %ul#nav-mobile.right.side-nav
      - if user_signed_in?
        - if current_user.admin?
          %li
            = link_to "Atrações dos Usuários", user_attractions_tools_path
        %li
          = link_to "Compartilhar", shares_path
        %li
          = link_to "Sair", destroy_user_session_path, method: :delete
      - else
        %li
          = link_to "Entrar", new_user_session_path
    = link_to "#", class: "button-collapse", "data-activates"=>"nav-mobile" do
      %i.mdi-navigation-menu

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    :javascript
      toast("#{msg}", 4000);

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Organizador de Atrações
    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body{"data-controller" => "#{controller.controller_name}", "data-action" => "#{controller.action_name}"}
    = render "layouts/header"
    .container
      .row
        = render "layouts/messages"
        = yield

app/views/layouts/home.html.haml
!!! 5
%html
  %head
    %title Organizador de Atrações
    = stylesheet_link_tag "home", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "home", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav
      .nav-wrapper
        %h1
          = link_to "Organizador de Atrações", root_path, class: "brand-logo"
        %ul#nav-mobile.right.side-nav
          %li
            = link_to "Entrar", new_user_session_path
        = link_to "#", class: "button-collapse", "data-activates"=>"nav-mobile" do
          %i.mdi-navigation-menu


    - flash.each do |name, msg|
      - if msg.is_a?(String)
        :javascript
          $(document).ready( function() {
            toast("#{msg}", 4000);
          });
    #index-banner.parallax-container
      .section.no-pad-bot
        .container
          %br/
          %br/
          %h1.header.center.grey-text.text-lighten-2 Organizador de Atrações
          .row.center
            %h5.header.col.s12.light Um aplicativo para gerenciar suas atrações e poder compartilhar
          .row.center
            %a#download-button.btn-large.waves-effect.waves-light.teal.lighten-1{:href => "#{new_user_registration_path}"} CRIE SUA CONTA
          %br/
          %br/
      .parallax
        = image_tag "background1.jpg"
    .container
      .section
        / Icon Section
        .row
          .col.s12.m4
            .icon-block
              %h2.center.brown-text
              %h5.center Speeds up development
              %p.light We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.
          .col.s12.m4
            .icon-block
              %h2.center.brown-text
              %h5.center User Experience Focused
              %p.light By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.
          .col.s12.m4
            .icon-block
              %h2.center.brown-text
              %h5.center Easy to work with
              %p.light We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.
    .parallax-container.valign-wrapper
      .section.no-pad-bot
        .container
          .row.center
            %h5.header.col.s12.light A modern responsive front-end framework based on Material Design
      .parallax
        = image_tag "background2.jpg"
    .container
      .section
        .row
          .col.s12.center
            %h3
            %h4 Contact Us
            %p.left-align.light Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
    .parallax-container.valign-wrapper
      .section.no-pad-bot
        .container
          .row.center
            %h5.header.col.s12.light A modern responsive front-end framework based on Material Design
      .parallax
        = image_tag "background3.jpg"
    %footer.page-footer.teal
      .container
        .row
          .col.l6.s12
            %h5.white-text Company Bio
            %p.grey-text.text-lighten-4 We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.
          .col.l3.s12
            %h5.white-text Settings
            %ul
              %li
                %a.white-text{:href => "#!"} Link 1
              %li
                %a.white-text{:href => "#!"} Link 2
              %li
                %a.white-text{:href => "#!"} Link 3
              %li
                %a.white-text{:href => "#!"} Link 4
          .col.l3.s12
            %h5.white-text Connect
            %ul
              %li
                %a.white-text{:href => "#!"} Link 1
              %li
                %a.white-text{:href => "#!"} Link 2
              %li
                %a.white-text{:href => "#!"} Link 3
              %li
                %a.white-text{:href => "#!"} Link 4
      .footer-copyright
        .container
          Made by
          %a.brown-text.text-lighten-3{:href => "http://materializecss.com"} Materialize

app/views/shares/index.html.haml
%h2.header
  Compartilhe suas atrações!
.divider
= form_tag send_attractions_shares_path, class: "col s12 form" do
  .row
    .col.s6
      %ul.check_list
        - @users.each do |user|
          %li
            = check_box_tag "share[user_ids[#{user.id}]]", user.id
            = label_tag "share[user_ids[#{user.id}]]", user.email
    .col.s6
      %ul.check_list
        - @attractions.each do |attraction|
          %li
            = check_box_tag "share[attraction_ids[#{attraction.id}]]", attraction.id
            = label_tag "share[attraction_ids[#{attraction.id}]]", attraction.name
  = render partial:'layouts/form_simple_action', :locals => {:text => "Compartilhar!"}

app/views/tools/_attractions_list.html.haml
- if @attractions.size > 0
  - @attractions.each do |attraction|
    %ul.card-panel.blue.lighten-5.blue-text
      %li
        %span
          = attraction.name
      %li
        %span
          = "Dia #{attraction.due_date.strftime("%d/%m/%Y")} às #{attraction.due_time.strftime("%H:%M")}"
      - if !attraction.midia.nil?
        %li
          %span
            = "Mídia para assitir: #{attraction.midia}"
- else
  Este usuário não possui atrações cadastradas

app/views/tools/fetch_attractions.js.erb
$(".user_" + <%= @user.id.to_s %> + "_attractions").html("<%= escape_javascript(render partial: 'attractions_list', locals: { attractions: @attractions } ) %>");

app/views/tools/user_attractions.html.haml
%h2.header
  Veja as atrações dos usuários
.divider
%ul.collapsible{"data-collapsible"=>"accordion"}
  - @users.each do |user|
    %li
      .collapsible-header
        = link_to user.username, fetch_attractions_tools_path(:user_id => user.id), :remote => true, class: "search_attractions"
      .collapsible-body
        %p{class: "user_#{user.id}_attractions"}
          %span.preloader-wrapper.big.active
            %span.spinner-layer.spinner-blue
              %span.circle-clipper.left
                %span.circle
              %span.gap-patch
                %span.circle
              %span.circle-clipper.right
                %span.circle
            %span.spinner-layer.spinner-red
              %span.circle-clipper.left
                %span.circle
              %span.gap-patch
                %span.circle
              %span.circle-clipper.right
                %span.circle
            %span.spinner-layer.spinner-yellow
              %span.circle-clipper.left
                %span.circle
              %span.gap-patch
                %span.circle
              %span.circle-clipper.right
                %span.circle
            %span.spinner-layer.spinner-green
              %span.circle-clipper.left
                %span.circle
              %span.gap-patch
                %span.circle
              %span.circle-clipper.right
                %span.circle